version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:18  # Use a Node.js 18 compatible Docker image
    steps:
      - checkout
      - run:
          name: Clean npm cache
          command: npm cache clean --force
      - run:
          name: Delete node_modules and package-lock.json
          command: rm -rf node_modules package-lock.json
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  test:
    jobs:
      - test  # Correct the job name to match the one defined above
