version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test: # This job will build and test your app
    executor: node/default # Use the default executor from the node orb
    steps:
      - checkout  # Pulls your source code from the repository
      - node/install-packages:
          pkg-manager: npm  # Install your npm dependencies
      - run:
          command: npm run test  # Run your test suite
          name: Run tests
      - run:
          command: npm run build  # Build your app (optional if you have a build step)
          name: Build app
      - persist_to_workspace:
          root: ~/project  # Save your project files for future jobs (if needed)
          paths:
            - .  # Persist the entire project directory

workflows:
  build_test:  # Workflow that just runs the build_and_test job
    jobs:
      - build_and_test  # Only this job is run, no deploy step
